# Generated by Django 5.2.11 on 2026-02-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'الرسائل', 'verbose_name_plural': 'الرسالة'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'الخبرات', 'verbose_name_plural': 'الخبرة'},
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name': 'البيانات الشخصية', 'verbose_name_plural': 'البيانات الشخصية'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'مشروع', 'verbose_name_plural': 'المشاريع'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'صور المشاريع', 'verbose_name_plural': 'صور المشروع'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'مهارة', 'verbose_name_plural': 'المهارات'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'وسائل الأتصال', 'verbose_name_plural': 'وسيلة الأتصال'},
        ),
        migrations.AddField(
            model_name='project',
            name='propertys',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='icon',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project/tech/'),
        ),
    ]
