# Generated by Django 5.2.11 on 2026-02-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live',
            field=models.URLField(blank=True, null=True),
        ),
    ]
