# Generated by Django 5.2.11 on 2026-02-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0003_alter_project_github_alter_project_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='kind',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
