# Generated by Django 5.2.11 on 2026-02-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0004_project_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'الرسالة', 'verbose_name_plural': 'الرسائل'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'وسيلة الأتصال', 'verbose_name_plural': 'وسائل التواصل'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='الموضوع'),
        ),
    ]
