# Generated by Django 5.2.11 on 2026-02-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0005_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='bio_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='location_ar',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='location_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='name_ar',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='title_ar',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='kind_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='kind_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='propertys_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='propertys_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
