# Generated by Django 5.2.11 on 2026-02-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0006_personalinfo_bio_ar_personalinfo_bio_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='brand',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='brand_ar',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='brand_en',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
